spring.application.name=HotelBooking-Backend


spring.datasource.url=jdbc:postgresql://localhost:5432/HotelBookingDB
spring.datasource.username=postgres
spring.datasource.password=database

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api/v1

jwt.secretKey=bhr3vojfv87g48gfbu4bgpub589gbfu45bguh458gbup4ug5b43

frontend.url=http://localhost:8080

stripe.secret.key=sk_test_51TzAiTCYlCAwXPEge7utdovWL9kEUrBHvikacpzMRfJTMGB7MIQJbFYcSIQ803DzfbTwXwZfIOol1iU6xO5jJj6f00hijeeBdC
stripe.webhook.secret=whsec_9cac6c8a318b8079d21af3ef98c8f10489beda6f0c12cc0a1adab4967771bb15